# Generated by Django 4.0 on 2023-11-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='position',
            field=models.CharField(choices=[('TOP', 'Верх'), ('BOTTOM', 'Низ'), ('LEFT', 'Лево'), ('RIGHT', 'Право'), ('CORNER', 'Угол')], default=1, max_length=6, verbose_name='Тип'),
            preserve_default=False,
        ),
    ]
