# Generated by Django 4.0 on 2023-11-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_walk',
            field=models.BooleanField(default=False, verbose_name='Мой ход'),
        ),
    ]
