# Generated by Django 4.0 on 2023-11-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0002_card_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='position',
            field=models.CharField(choices=[('TOP', 'Верх'), ('BOTTOM', 'Низ'), ('LEFT', 'Лево'), ('RIGHT', 'Право'), ('CORNER', 'Угол')], max_length=7, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='card',
            name='type',
            field=models.CharField(choices=[('DEFAULT', 'Обычная'), ('EVENT', 'Событие')], max_length=7, verbose_name='Тип'),
        ),
    ]
