# Generated by Django 4.0 on 2023-11-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0003_alter_card_position_alter_card_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='position',
            field=models.CharField(blank=True, choices=[('TOP', 'Верх'), ('BOTTOM', 'Низ'), ('LEFT', 'Лево'), ('RIGHT', 'Право'), ('CORNER', 'Угол')], max_length=7, null=True, verbose_name='Позиция'),
        ),
    ]
