# Generated by Django 4.0 on 2023-11-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0004_alter_card_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='card',
            name='position',
            field=models.CharField(choices=[('TOP', 'Верх'), ('BOTTOM', 'Низ'), ('LEFT', 'Лево'), ('RIGHT', 'Право'), ('CORNER', 'Угол')], max_length=7, verbose_name='Позиция'),
        ),
    ]
