# Generated by Django 4.0 on 2023-11-06 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0002_user_is_walk'),
        ('models_app', '0005_alter_card_cost_alter_card_position'),
    ]

    operations = [
    ]
