# Generated by Django 4.0 on 2023-11-06 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0007_room_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='index',
            field=models.IntegerField(default=1, verbose_name='Номер'),
            preserve_default=False,
        ),
    ]
