# Generated by Django 4.0 on 2023-11-06 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0008_card_index'),
        ('models_app', 'added_cards'),
    ]

    operations = [
    ]
