# Generated by Django 4.0 on 2023-11-06 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0009_merge_0008_card_index_added_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='index',
            field=models.IntegerField(default=0, verbose_name='Номер'),
        ),
    ]
