# Generated by Django 4.0 on 2023-11-07 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0011_user_position'),
        ('models_app', 'added_questions'),
    ]

    operations = [
    ]
